// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (-1016169464)
#define NOTOSERIF_14_FONT_ID (-1949882134)
#define NOTOSERIF_16_FONT_ID (-450474652)
#define NOTOSERIF_18_FONT_ID (2116598001)
#define NOTOSANS_12_FONT_ID (-228736465)
#define NOTOSANS_14_FONT_ID (1922852609)
#define NOTOSANS_16_FONT_ID (-1573714306)
#define NOTOSANS_18_FONT_ID (-561755375)
#define UI_10_FONT_ID (-854931893)
#define UI_12_FONT_ID (824072906)
#define UI_14_FONT_ID (-1485668874)
#define UI_16_FONT_ID (1229919197)
#define UI_18_FONT_ID (-1003220843)
#define HEADER_FONT_ID (554125389)
#define SCRIPT_FONT_ID (1574218903)
#define SCRIPT_SMALL_FONT_ID (-1619157203)
#define SMALL_FONT_ID (-169211286)
#define MICRO_FONT_ID (1228448282)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(HEADER_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(MICRO_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SCRIPT_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SCRIPT_SMALL_FONT_ID != 0, "Font ID collision with sentinel");
